package com.example.xiudd.sese.greenDAO;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.xiudd.sese.greenDAO.DownloadDAO;

import com.example.xiudd.sese.greenDAO.DownloadDAODao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig downloadDAODaoConfig;

    private final DownloadDAODao downloadDAODao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        downloadDAODaoConfig = daoConfigMap.get(DownloadDAODao.class).clone();
        downloadDAODaoConfig.initIdentityScope(type);

        downloadDAODao = new DownloadDAODao(downloadDAODaoConfig, this);

        registerDao(DownloadDAO.class, downloadDAODao);
    }
    
    public void clear() {
        downloadDAODaoConfig.clearIdentityScope();
    }

    public DownloadDAODao getDownloadDAODao() {
        return downloadDAODao;
    }

}
